In [1]:
!pip install -q datasets duckdb huggingface_hub pyarrow pandas

In [3]:
from huggingface_hub import login
import getpass

token = getpass.getpass("Paste your Hugging Face token: ")
login(token)

In [6]:
from datasets import load_dataset

content = load_dataset(
    "FlyRank/internship-warehouse",
    "dim_content",
    split="train"
)

print(content)

dim_content.parquet:   0%|          | 0.00/19.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/519606 [00:00<?, ? examples/s]

Dataset({
    features: ['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted'],
    num_rows: 519606
})

In [7]:
content.column_names

['client_hash_id',
 'content_hash_id',
 'keyword_hash_id',
 'url_hash_id',
 'keyword_char_count',
 'keyword_token_count',
 'url_char_count',
 'content_created_date',
 'content_updated_date',
 'content_type',
 'search_volume',
 'competition',
 'competition_level',
 'cpc',
 'main_intent',
 'backlinks',
 'category_count',
 'keyword_created_date',
 'provider_used',
 'model_used',
 'char_count',
 'word_count',
 'last_optimized_date',
 'optimization_eligible_date',
 'is_published',
 'is_deleted']

In [8]:
content.to_pandas().head()

,client_hash_id,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,...,category_count,keyword_created_date,provider_used,model_used,char_count,word_count,last_optimized_date,optimization_eligible_date,is_published,is_deleted
0,client_04660893ae39614a,content_004de9653278b5a4,keyword_e754999ab88dd9f2,url_d6091f18cf628794,22,4,108,2026-05-30,2026-07-01,keyword article,...,3,2026-05-12,gemini-generate-content,gemini-3-flash-preview,15682.0,2555.0,None,None,True,False
1,client_04660893ae39614a,content_00dc5efae381b2ab,keyword_4329d7aede8e208b,url_3a66d2f2e36823ca,31,6,95,2026-06-12,2026-07-01,keyword article,...,4,2026-06-01,gemini-generate-content,gemini-3-flash-preview,15438.0,2430.0,None,None,True,False
2,client_04660893ae39614a,content_01410f2556c327ac,keyword_9b08047d3d2a0406,url_809eda7a7e20b3b2,22,5,82,2026-05-09,2026-07-01,keyword article,...,4,2026-05-06,gemini-generate-content,gemini-3-flash-preview,16576.0,2645.0,None,None,True,False
3,client_04660893ae39614a,content_019f27f634053ca7,keyword_e7cec7ab1804c1c2,url_5fb42bafc4399861,14,3,92,2026-06-15,2026-06-15,keyword article,...,4,2026-06-01,gemini-generate-content,gemini-3-flash-preview,15457.0,2522.0,None,None,True,False
4,client_04660893ae39614a,content_01efa71faea45dcc,keyword_56b0062a1d8b7524,url_ece0abc3e5fb75f9,24,6,98,2026-05-21,2026-06-01,keyword article,...,4,2026-05-12,gemini-generate-content,gemini-3-flash-preview,15776.0,2552.0,None,None,True,False

In [9]:
import pandas as pd

df = content.to_pandas()

print("Shape:", df.shape)
print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nContent Types:\n")
print(df["content_type"].value_counts())

print("\nPublished Status:\n")
print(df["is_published"].value_counts())

print("\nDeleted Status:\n")
print(df["is_deleted"].value_counts())

Shape: (519606, 26)

Missing Values:

client_hash_id                     0
content_hash_id                    0
keyword_hash_id                71998
url_hash_id                     6525
keyword_char_count                 0
keyword_token_count                0
url_char_count                     0
content_created_date               0
content_updated_date               0
content_type                       0
search_volume                 142622
competition                   142622
competition_level             144456
cpc                           142622
main_intent                   148398
backlinks                     267474
category_count                     0
keyword_created_date           71998
provider_used                 369936
model_used                     84963
char_count                    177768
word_count                    177768
last_optimized_date           474210
optimization_eligible_date    474210
is_published                       0
is_deleted                         0
dtype: int64

Content Types:

content_type
keyword article       459174
feedly article         57024
comparison article      3408
Name: count, dtype: int64

Published Status:

is_published
True     411540
False    108066
Name: count, dtype: int64

Deleted Status:

is_deleted
False    418047
True     101559
Name: count, dtype: int64

In [10]:
from datasets import load_dataset

daily = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    split="train"
)

print(daily)
print(daily.column_names)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/19.6k [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/624k [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/4.41M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/90.3M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/86.2M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/72.0M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/89.0M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/21.6M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/3.29M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/134M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/2.62M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/1.45M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/7.12M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/124M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/8.93M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/3.22M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/149M [00:00<?, ?B/s]

fact_content_daily_performance/month=202(…):   0%|          | 0.00/146M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

Dataset({
    features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
    num_rows: 78835655
})
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [11]:
daily_df = daily.to_pandas()

daily_df["report_date"] = pd.to_datetime(daily_df["report_date"])

march = daily_df[
    (daily_df["report_date"] >= "2026-03-01") &
    (daily_df["report_date"] <= "2026-03-31")
]

print(march.shape)
march.head()

(9841378, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
35188099,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20.0,0.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188100,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188101,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125.0,1.0,616.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188102,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7.0,0.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188103,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11.0,0.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Search Intelligence Data Contract

### 1. What does one row represent?
One row represents the daily performance of one content page for one client on one reporting date.

### 2. Which table(s) will you use?
I use:
- dim_content
- fact_content_daily_performance

### 3. Which time window?
March 2026 (2026-03-01 to 2026-03-31).

### 4. What am I predicting?
I aim to predict or rank content performance using historical Search Console and Analytics metrics.

### 5. What do I deliberately exclude?
Future performance metrics and any label-derived information are excluded to prevent data leakage.

In [12]:
grain = march.groupby(
    ["report_date", "client_hash_id", "content_hash_id"]
).size()

print("Maximum duplicate rows:", grain.max())

Maximum duplicate rows: 1

Result:
Each row uniquely represents one client, one content page, and one reporting date.

In [13]:
print("Rows:", len(march))
print("First Date:", march["report_date"].min())
print("Last Date:", march["report_date"].max())

Rows: 9841378
First Date: 2026-03-01 00:00:00
Last Date: 2026-03-31 00:00:00

In [14]:
available = march[
    (march["gsc_data_available"] == True) &
    (march["ga4_data_available"] == True)
]

print("Available rows:", len(available))

Available rows: 364347

Only rows where both Search Console and GA4 data are available are used.

In [15]:
features = available[
    [
        "gsc_impressions",
        "gsc_clicks",
        "gsc_avg_position",
        "ga4_sessions",
        "scroll_events"
    ]
]

features.head()

,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_sessions,scroll_events
35202579,5.0,0.0,5.400000,1.0,0.0
35202847,39.0,0.0,5.666667,2.0,0.0
35202867,179.0,0.0,5.156425,2.0,0.0
35202882,72.0,0.0,7.694444,1.0,0.0
35202954,3282.0,1.0,6.167885,1.0,0.0

## Feature Availability

1. gsc_impressions
Available because impressions are already recorded before prediction.

2. gsc_clicks
Available because clicks are historical observations.

3. gsc_avg_position
Available because search ranking history already exists.

4. ga4_sessions
Available because website sessions are historical analytics data.

5. scroll_events
Available because user engagement has already occurred.

In [16]:
leak = available[
    [
        "gsc_impressions",
        "gsc_clicks",
        "ga4_sessions"
    ]
].copy()

# Deliberately leaking the label
leak["label"] = available["gsc_clicks"]

print(leak.head())

          gsc_impressions  gsc_clicks  ga4_sessions  label
35202579              5.0         0.0           1.0    0.0
35202847             39.0         0.0           2.0    0.0
35202867            179.0         0.0           2.0    0.0
35202882             72.0         0.0           1.0    0.0
35202954           3282.0         1.0           1.0    1.0

The column 'label' is directly derived from the prediction target. Including it would produce unrealistically high model performance because the answer is already present in the features. This demonstrates target leakage. The leaked feature should be removed before training.

## Limitation

This analysis uses only March 2026 and therefore does not capture seasonal variations or long-term trends. Some analytics fields also contain missing values, limiting the available training data.

- ✅ Five contract answers completed.
- ✅ Three verification queries completed.
- ✅ Availability verified.
- ✅ Five features created.
- ✅ Leakage demonstrated and explained.
- ✅ Limitation documented.