In [5]:
import pandas as pd

# Load the starter dataset
df = pd.read_csv("../../data/raw/content_refresh_anonymized.csv")

# Display basic information
print("Shape:", df.shape)
df.head()

Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [6]:
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

# Week 2 - ML Task Framing

## 1. My Lane as an ML Task

**Task Type:** Classification

The goal is to predict whether a content page is likely to become a high-performing page based on historical SEO and engagement metrics. Instead of manually reviewing every page, a machine learning model can classify pages into high-performing and low-performing categories to help prioritize content optimization.

## 2. Target (Proxy)

Since the dataset does not contain a direct label called **High Performing**, we create our own target.

**Target:** `high_performance`

Definition:

- **1** → High Performing Content
- **0** → Low Performing Content

We will use the median CTR (Click Through Rate) as the threshold to create this target.

In [7]:
median_ctr = df["ctr"].median()

df["high_performance"] = (df["ctr"] > median_ctr).astype(int)

df[["ctr", "high_performance"]].head()

    ctr  high_performance
0  0.76                 1
1  0.05                 0
2  0.09                 1
3  0.49                 1
4  0.13                 1

## 3. Success Metric

### Primary Metric: F1 Score

I selected **F1 Score** because this is a binary classification problem. It balances Precision and Recall, making it suitable when the classes may not be perfectly balanced.

Other useful metrics include Accuracy, Precision, Recall, and ROC-AUC.

In [8]:
print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (30000, 45)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,high_performance
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4,1
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7,0
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9,1
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8,1
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7,1

## 4. Unit of Analysis

One row in this dataset represents **one content page**.

Each content page contains SEO metrics, engagement metrics, search performance, and content-related information.

The machine learning model predicts whether that single content page is likely to be a high-performing page.

## 4. Unit of Analysis

One row in this dataset represents **one content page**.

Each content page contains SEO metrics, engagement metrics, search performance, and content-related information.

The machine learning model predicts whether that single content page is likely to be a high-performing page.

## Content Action

The output of this machine learning model can be used to:

- Identify content pages that need optimization.
- Prioritize pages for SEO improvements.
- Help content teams decide which pages should be refreshed first.
- Improve overall search visibility and user engagement.

## 6. Self Check

- ✅ ML task type identified
- ✅ Target (proxy) defined
- ✅ Success metric selected
- ✅ Unit of analysis shown
- ✅ Real dataframe displayed
- ✅ Target column created
- ✅ Explained why ML is better than a fixed rule
- ✅ Connected the prediction to a real business action